-- Active: 1660546976939@@zubdb.cabyoqiwyaa1.us-west-1.rds.amazonaws.com@5432@postgres@rawinput

--- copy csv ke table penjualan
--pake pg admin jadinya, wkwkkw
--- sekarang test koneksi ke GDS
--- GDS loading lama dan tidak konek ke posgres muncul error : "Sorry, we encountered an error and were unable to complete your request"
--- sepertinya kalau pake cloud posgre harus pake SSL certificate
--- ternyata udah ada jawabannya di stack overflow
--- masih mencari running codenya dimana, apakah di python ?
--- aku running di GitBash jalan zub trus di tanya tanya kan, lengkapnya aku kasih di notion ya
--- udah muncul dooongggg, udah dipindah ke folder lain biar g keupload ke git haha
